version: "3"
services:
  neko:
    image: "vsarath732/vb"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8081:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
